// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqLrJzDSYGnFf6IhXHxFsn7x2reYLXQAk',
    appId: '1:215977533351:web:e360ef9aae86a75cef2082',
    messagingSenderId: '215977533351',
    projectId: 'gss-project-prod',
    authDomain: 'gss-project-prod.firebaseapp.com',
    databaseURL: 'https://gss-project-prod-default-rtdb.firebaseio.com',
    storageBucket: 'gss-project-prod.appspot.com',
    measurementId: 'G-VV0LJCSTSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFXid8iVxuZ4HBaa92ruzj_P7Xm1YXVtw',
    appId: '1:215977533351:android:c03468c9c747262eef2082',
    messagingSenderId: '215977533351',
    projectId: 'gss-project-prod',
    databaseURL: 'https://gss-project-prod-default-rtdb.firebaseio.com',
    storageBucket: 'gss-project-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL4Q-amL-xGB9wDZS6u8qGzGueM1bGMbc',
    appId: '1:215977533351:ios:da58d58df223b7cbef2082',
    messagingSenderId: '215977533351',
    projectId: 'gss-project-prod',
    databaseURL: 'https://gss-project-prod-default-rtdb.firebaseio.com',
    storageBucket: 'gss-project-prod.appspot.com',
    iosClientId: '215977533351-67t53n6olqhl0dp37kcshnfbnb4q5f87.apps.googleusercontent.com',
    iosBundleId: 'com.example.atkSystemGa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL4Q-amL-xGB9wDZS6u8qGzGueM1bGMbc',
    appId: '1:215977533351:ios:da58d58df223b7cbef2082',
    messagingSenderId: '215977533351',
    projectId: 'gss-project-prod',
    databaseURL: 'https://gss-project-prod-default-rtdb.firebaseio.com',
    storageBucket: 'gss-project-prod.appspot.com',
    iosClientId: '215977533351-67t53n6olqhl0dp37kcshnfbnb4q5f87.apps.googleusercontent.com',
    iosBundleId: 'com.example.atkSystemGa',
  );
}
